DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;
drop table if exists postagem cascade;
drop table if exists curtida cascade;
drop table if exists comentario cascade;
drop table if exists amizade cascade;

CREATE TABLE usuario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	senha VARCHAR(128) NOT NULL,
	data_nascimento date not null,
	imagem VARCHAR(512),
	apelido VARCHAR(50),
	ativo BOOLEAN NOT NULL
);
ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY (id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE (email);

CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);
ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


create table postagem (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id bigint not null,
	titulo varchar(100) not null,
	descricao varchar(512) not null,
	imagem VARCHAR(512),
	data_inclusao timestamp not null,
	publico boolean not null
);
alter table postagem add constraint pk_postagem primary key (id);
alter table postagem add constraint fk_postagem_usuario foreign key (usuario_id) references usuario;

create table curtida (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	postagem_id bigint not null,
	usuario_id bigint not null
);
alter table curtida add constraint pk_curtida primary key (id);
alter table curtida add constraint uk_curtida unique (postagem_id, usuario_id);
alter table curtida add constraint fk_curtida_usuario foreign key (usuario_id) references usuario;
alter table curtida add constraint fk_curtida_postagem foreign key (postagem_id) references postagem;

create table comentario (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	postagem_id bigint not null,
	usuario_id bigint not null,
	texto varchar(512) not null,
	data_inclusao timestamp not null
);
alter table comentario add constraint pk_comentario primary key (id);
alter table comentario add constraint fk_comentario_usuario foreign key (usuario_id) references usuario;
alter table comentario add constraint fk_comentario_postagem foreign key (postagem_id) references postagem;

create table amizade (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	usuario_id_ativo bigint not null,
	usuario_id_amigo bigint not null,
	situacao varchar(20) not null,
	data_pedido timestamp not null
);
alter table amizade add constraint pk_amizade primary key (id);
alter table amizade add constraint fk_amizade_usuario_ativo foreign key (usuario_id_ativo) references usuario;
alter table amizade add constraint fk_amizade_usuario_amigo foreign key (usuario_id_amigo) references usuario;